[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
repository.workspace = true

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
clap.workspace = true
indoc.workspace = true
toml.workspace = true
